### PR TITLE
Task 3 draft

### PR DESCRIPTION
**Pull request by oshnix**

### CODE REVIEW

**Comment by fidopaca** [comment]
Thank you for your work. You seem to have done a lot. It doesn't matter if the app is running or not. But to give a more accurate rating, Is it possible to add a description to the PR? I really don't want to ignore your work.

**Comment by mvedataydin** [comment]
@oshnix Hello, Great work on the PR!
It would be amazing if you could share the Frontend Repository + Lambda service URL's for us to complete the cross-check review properly. 
Thanks!

**Comment by oshnix** [comment]
@mvedataydin Hello, that's a link to FE repo
https://github.com/oshnix/shop-vue-vuex-cloudfront

And that's a link to API
https://3584uwmg4l.execute-api.eu-west-1.amazonaws.com/dev/products/

**Review by mvedataydin — APPROVED** [review]
Hello @oshnix , great job on the PR, and thank you for the links.
 Here is my cross review comment, please let me know if I am missing anything:

- [x] Product-service serverless config contains configuration for 2 lambda functions, API is not working at all, but YAML configuration is correct
- [x] The getProductsList OR getProductsById lambda function returns a correct response (POINT1)
- [x] The getProductsById AND getProductsList lambda functions return a correct response code (POINT2)
- [x] Your own Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend. AND POINT1 and POINT2 are done.
- [ ] Async/await is used in lambda functions
- [x] ES6 modules are used for product-service implementation
- [x] Webpack is configured for product-service (or esbuild)
- [ ] Lambda handlers are covered by basic UNIT tests (NO infrastructure logic is needed to be covered)
- [x] Lambda handlers (getProductsList, getProductsById) code is written not in 1 single module (file) and separated in codebase.
- [x] Main error scenarios are handled by API ("Product not found" error).(Currently not handled)
- [ ] SWAGGER documentation is created for product-service


Score: 8/11

**Pull request merged**
